version: "3.8"
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ".:/app"
    image: my_app
    mem_reservation: "1024m"
    depends_on:
      - db
      - redis
    ports:
      - '3000:3000'     
  db:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: "redis:7-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis_data:/data
volumes:
  postgres:
