version: "2"
services:
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    volumes:
      - ".:/docker-service"
    image: my_app
    mem_reservation: "1024m"
    depends_on:
      - db
    ports:
      - '3000:3000'     
  db:
    image: postgres:13
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres:
